### ISSUE TITLE
How can ı echo seed / leech status 

### ISSUE THREAD

**Issue by DejavuTr** [tcz/PHPTracker#29]
How Can ı echo seed and leech status torrent announced ? sorry my bad english

**Comment by jaitaiwan** [comment]
@necrose99 would you mind updating your above comment with a link to a public gist with that code? It would help to clean this issue up.

@DejavuTr Scraping is coming in a future version. Stay tuned!

**Comment by jaitaiwan** [comment]
Closing this as #26 will address this.

**Comment by necrose99** [comment]
https://github.com/jmesmon/rwt/blob/master/tracker_modify.pl hear it is amound others some can do the same in python on bitbucket,

**Comment by jaitaiwan** [comment]
Cheers
