### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by jaitaiwan** [tcz/PHPTracker#33]
I'm wondering if this project is still active as I'm wanting to use it as a deployment strategy for Rocketeer. If its not active I'd love to help take it over, and if it is active, I'd love to become an active contributor. I have a vested interest in seeing this project thrive.

**Comment by tcz** [comment]
Hi Daniel,

Contributions are always welcome and I'm gonna respond to PRs in a timely
manner. I might even help implementing what you need. I didn't touch the
code for some time though.

Can you tell me what are your pain points with the current version?

**Comment by jaitaiwan** [comment]
Hi Zoltan,

There's no pain points at the moment :) I guess what I'm offering is help with accepting PR's and reviewing them. Aka being an official contributor and helping to bring the project towards a prime time release. Should help to speed up the projects maturity as well as give it some more visibility by being a replacement for lg/murder in php form.

**Comment by tcz** [comment]
Sounds great to me. How do we proceed?

**Comment by jaitaiwan** [comment]
Lets chat via email or skype:
dan@centricwebestate.com
jaitaiwan

Kind Regards,

Daniel J Holmes

On Thu, May 7, 2015 at 2:58 AM, Zoltan Toth-Czifra <notifications@github.com
> wrote:

> Sounds great to me. How do we proceed?

**Comment by jaitaiwan** [comment]
I'm in AEST time :)

**Comment by jaitaiwan** [comment]
Hey @tcz are you wanting to keep going with your project? I get the vibe that you're not all that interested in it...

Let me know because if not, it might be best for me to just fork the project and point future people via the readme to the forked repo and perhaps work with you to pay for and take over the domain as well.

**Comment by tcz** [comment]
Hi @jaitaiwan,

Sorry for not being very responsive. I have a lot on my plate, some important projects finishing at work, I cannot dedicate any time for PHPUnit now. However, you've been added as collaborator, I was hoping you can get an active role in running this project, that is also making decisions and not depending on me for everything. :)

**Comment by jaitaiwan** [comment]
He's alive!!! Great, there's a lot of huge structural changes I wanted to
make so I'm glad that I'm able to make them. I really wasn't clear on the
depth of control you wanted me to have.

Is there any code you've done but yet to finish or push to the project?

**Comment by tcz** [comment]
Not at the moment, I'm super excited to see the changes you are proposing!
:-)
