### ISSUE TITLE
Error when creating torrent 

### ISSUE THREAD

**Issue by genaside** [tcz/PHPTracker#34]
For  php version 5.4 I get:
> PHP Fatal error:  Declaration of PHPTracker_Bencode_Value_Container::__construct() must be compatible with PHPTracker_Bencode_Value_Abstract::__construct($value) in /xxxx/PHPTracker/Bencode/Value/Container.php on line 63

Ive fixed it by  by removing `array` from `public function __construct( array $value = null )`, but i got different error after: `PHP Strict Standards:  Only variables should be passed by reference in /xxxx/PHPTracker/Torrent.php on line 219`

I am not sure why you call reset twice on the same array `reset( reset( $announce_list ) )`, but one reset seems to work `reset( $announce_list )`.

After the fix. things seems to work

** Collaborator Update: Fixed formatting for readability

**Comment by jaitaiwan** [comment]
Thanks for that! Great issue. Would you be up to providing a PR to
introduce this change?

Kind Regards,

Daniel J Holmes

**Comment by genaside** [comment]
ofcourse, i can do it now

**Comment by jaitaiwan** [comment]
All of the tests are failing prior to your pull request. So it's not you, but if you'd like to help get the tests passing again that would be a huge help

**Comment by jaitaiwan** [comment]
Referencing PR #35 for completeness.
