### ISSUE TITLE
Licence Clarification

### ISSUE THREAD

**Issue by jaitaiwan** [tcz/PHPTracker#37]
Hi @tcz 

Thought I would open an issue here to discuss the licencing of this project. I noticed it doesn't seem tied to any one standard like GPLv3 or BSD. Is your licence based off any of these or can we perhaps discuss moving to a standard to make future contributions more appealing?

**Comment by tcz** [comment]
The currently used licence is this: http://opensource.org/licenses/BSD-3-Clause
It's a fairly common version of the BSD licence.

**Comment by jaitaiwan** [comment]
Cool, I'll update the README's etc to reference that its a BSD 3 clause.

**Comment by tcz** [comment]
I don't think it's needed, it's pretty clear on the website and in the repo
too

**Comment by jaitaiwan** [comment]
You're the boss :smile:
