### ISSUE TITLE
Private Torrents

### ISSUE THREAD

**Issue by drjoju** [tcz/PHPTracker#4]
Hello,

for a new version you can add the private torrent flag to the file. You can do it adding the line

'private'  		=> $this->__get( 'privateTorrent' ),

to the createTorrentFile function in Torrent.php file and the same line to the calculateInfoHash function.

You need to public the privateTorrent var int PHPTracker_Torrent class to change it.

Best regards

By the way. Greeting from Barcelona

**Comment by jaitaiwan** [comment]
Referencing #42 for completeness.

**Comment by jaitaiwan** [comment]
Addressed by #42
