### ISSUE TITLE
Adding signal handlers to seed server

### ISSUE THREAD

**Issue by tcz** [tcz/PHPTracker#7]
We need to handle SIGINT, SIGQUIT, SIGABRT, SIGKILL both in parent processes and children to release resources properly as well as propagating signals to the whole process tree.

When signal comes:

- remove signal handler (SIG_IGN)
- iterate over children and send signals to them
- close resources and terminate

Also we need to change the wait function in the guardian processes according to the following:

- reading status
- checking pcntl_wifsignaled() for the dead process
- if it's yes, get signal with pcntl_wstopsig() and send it to the current process (guardian)

**Comment by jaitaiwan** [comment]
Closing as we are moving process handling into an external library as per #44
